name: test

on:
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.17.0
      - name: "Run tests"
        run: |
          go install github.com/jstemmer/go-junit-report
          make test | go-junit-report 2>&1 > unit-test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        if: always()
        with:
          check_name: "Unit Tests"
          report_paths: unit-test-results.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.17.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
